#
# This source file is part of the Apodini open source project
#
# SPDX-FileCopyrightText: 2021 Paul Schmiedmayer and the project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - develop
      - feature/release0.1.0
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  macos:
    name: macOS ${{ matrix.configuration }}
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        configuration: [debug, release, release_testing]
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1.2.3
      with:
        xcode-version: latest
    - uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
    - name: Check Xcode version
      run: xcodebuild -version
    - name: Check Swift version
      run: swift --version
    - name: Release Build
      if: matrix.configuration == 'release'
      run: swift build -c release
    - name: Release Build & Test
      if: matrix.configuration == 'release_testing'
      run: swift test -c release -Xswiftc -enable-testing -Xswiftc -DRELEASE_TESTING
    - name: Debug Build & Test
      if: matrix.configuration == 'debug'
      run: swift test -c debug --enable-code-coverage -Xswiftc -DCOVERAGE
    - name: Convert coverage report
      if: matrix.configuration == 'debug'
      run: xcrun llvm-cov export -format="lcov" .build/debug/ApodiniMigratorPackageTests.xctest/Contents/MacOS/ApodiniMigratorPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
    - name: Test Generating Docs
      if: ${{ false }} #disabled
      run: |
          xcodebuild docbuild -scheme ApodiniMigrator -destination platform=macOS,arch=x86_64 #-derivedDataPath ./.xcodebuild
          cp -r $(find ./.xcodebuild -type d -name '*.doccarchive') ./ApodiniMigrator.doccarchive
          echo "The DocC archive can be found at ./ApodiniMigrator.doccarchive"
  linux:
    name: Linux ${{ matrix.linux }} ${{ matrix.configuration }}
    container:
      image: swiftlang/swift:nightly-5.5-${{ matrix.linux }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linux: [bionic, focal, amazonlinux2, centos8]
        configuration: [debug, release, release_testing]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-${{matrix.linux}}-spm-${{ hashFiles('Package.resolved') }}
    - name: Check Swift version
      run: swift --version
    - name: Release Build
      if: matrix.configuration == 'release'
      run: swift build -c release
    - name: Release Build & Test
      if: matrix.configuration == 'release_testing'
      run: swift test -c release -Xswiftc -enable-testing --enable-test-discovery
    - name: Debug Build & Test
      if: matrix.configuration == 'debug'
      run: swift test -c debug

