#
# This source file is part of the Apodini open source project
#
# SPDX-FileCopyrightText: 2021 Paul Schmiedmayer and the project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
#
# SPDX-License-Identifier: MIT
#

name: Update

on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:
  spm_update:
    name: Swift Package Update
    uses: Apodini/.github/.github/workflows/spm-update.yml@v1
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
